/*
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.tests

import com.fearlesstyrant.sephirah.sephirah.FormulaModel
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(SephirahInjectorProvider)
class SephirahParsingTest {
	@Inject
	ParseHelper<FormulaModel> parseHelper
	
	@Test
	def void loadModel() {
    	val result = parseHelper.parse('''
        	SephirahDoc parsingSmokeTest

        	var score = 10;

        	score;
	    ''')

    	Assertions.assertNotNull(result)

	    val errors = result.eResource.errors
	    Assertions.assertTrue(
    	    errors.isEmpty,
        	'''Unexpected errors: «errors.join(", ")»'''
    	)
	}
	
	@Test
	def void loadModelWithImport() {
    	val result = parseHelper.parse('''
        	SephirahDoc importSmokeTest

        	import math_helpers;

        	var score = 10;

        	score;
    	''')

    	Assertions.assertNotNull(result)

    	val errors = result.eResource.errors
    	Assertions.assertTrue(
        	errors.isEmpty,
        	'''Unexpected errors: «errors.join(", ")»'''
    	)

    	Assertions.assertEquals(1, result.imports.size)
    	Assertions.assertEquals("math_helpers", result.imports.get(0).module)
	}
	
	@Test
	def void loadModelWithAliasedImport() {
    	val result = parseHelper.parse('''
        	SephirahDoc aliasedImportSmokeTest

        	import math.helpers as math;

        	var score = 10;

        	score;
    	''')

    	Assertions.assertNotNull(result)

    	val errors = result.eResource.errors
    	Assertions.assertTrue(
        	errors.isEmpty,
        	'''Unexpected errors: «errors.join(", ")»'''
    	)

    	Assertions.assertEquals(1, result.imports.size)
    	Assertions.assertEquals("math.helpers", result.imports.get(0).module)
    	Assertions.assertEquals("math", result.imports.get(0).alias)
	}
}
