/*
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.ide;


/**
 * Use this class to register ide components.
 */
public class SephirahIdeModule extends AbstractSephirahIdeModule {
}
