/*
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.ide;

import com.fearlesstyrant.sephirah.SephirahRuntimeModule;
import com.fearlesstyrant.sephirah.SephirahStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SephirahIdeSetup extends SephirahStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SephirahRuntimeModule(), new SephirahIdeModule()));
	}
	
}
