/*
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SephirahAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/fearlesstyrant/sephirah/parser/antlr/internal/InternalSephirah.tokens");
	}
}
