/*
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.ui;

import com.fearlesstyrant.sephirah.ui.internal.SephirahActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SephirahExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SephirahActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SephirahActivator activator = SephirahActivator.getInstance();
		return activator != null ? activator.getInjector(SephirahActivator.COM_FEARLESSTYRANT_SEPHIRAH_SEPHIRAH) : null;
	}

}
