/*
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.validation;

import java.util.*;
import java.math.BigDecimal;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.nodemodel.ICompositeNode;
import org.eclipse.xtext.nodemodel.util.NodeModelUtils;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.ValidationMessageAcceptor;

import com.fearlesstyrant.sephirah.sephirah.*;
import com.fearlesstyrant.sephirah.tools.*;
import com.fearlesstyrant.sephirah.tools.value.SephirahValue;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SephirahValidator extends AbstractSephirahValidator {

	public static final String CODE_PREFIX = "com.fearlesstyrant.sephirah.";
	public static final String NORMALIZABLE = CODE_PREFIX + "normalizable_expression";
	public static final String UNDECLARED_VARIABLE = CODE_PREFIX + "undeclared_variable";
	public static final String UNUSED_VARIABLE = CODE_PREFIX + "unused_variable";
	public static final String DUPLICATE_VARIABLE = CODE_PREFIX + "duplicate_variable";
	public static final String NO_VARIABLE = CODE_PREFIX + "no_variable";
	public static final String EVALUATION_RESULT = CODE_PREFIX + "evaluation_result";
	public static final String CYCLICAL_REFERENCE = CODE_PREFIX + "cyclical_reference";
	public static final String DUPLICATE_FUNCTION = CODE_PREFIX + "duplicate_function";
	public static final String BUILTIN_FUNCTION_CONFLICT = CODE_PREFIX + "builtin_function_conflict";
	public static final String CYCLICAL_FUNCTION = CODE_PREFIX + "cyclical_function";
	public static final String UNKNOWN_FUNCTION = CODE_PREFIX + "unknown_function";
	public static final String FUNCTION_ARITY = CODE_PREFIX + "function_arity";
	public static final String DUPLICATE_PARAMETER = CODE_PREFIX + "duplicate_parameter";
	
	@Check
	public void checkBuiltinFunctionConflict(Definition definition) {
		String name = definition.getName();
		
		if(name == null || name.isBlank()) {
			return;
		}
		
		if (Methods.previewRegistry().contains(name) || Methods.standardRegistry().contains(name)) {
	        error("Function name " + name + " conflicts with a built-in function.",
	                SephirahPackage.Literals.DEFINITION__NAME,
	                BUILTIN_FUNCTION_CONFLICT,
	                name);
	    }
	}
	
	@Check
	public void checkCyclicalFunctionReference(Definition definition) {
		FormulaModel model = EcoreUtil2.getContainerOfType(definition, FormulaModel.class);
		
		if(model == null) {
			return;
		}
		
		String name = definition.getName();
		
		if(name == null || name.isBlank()) {
			return;
		}
		
		try {
			checkFunctionCycle(model, name, new ArrayDeque<>());
		} catch (IllegalStateException exception) {
	        error(exception.getMessage(),
	                SephirahPackage.Literals.DEFINITION__NAME,
	                CYCLICAL_FUNCTION,
	                name);
	    }
	}
	
	@Check
	public void checkCyclicalVariableReference(VariableAssignment assignment) {
		FormulaModel model = EcoreUtil2.getContainerOfType(assignment, FormulaModel.class);
		
		if(model == null || assignment.getName() == null || assignment.getValue() == null) {
			return;
		}
		
		try {
			ModuleValueResolver resolver = new ModuleValueResolver(model, 
					Methods.previewRegistry());
			
			resolver.resolveValue(assignment.getName());
		} catch(IllegalStateException exception) {
			error(exception.getMessage(),
					SephirahPackage.Literals.ASSIGNMENT__NAME,
					CYCLICAL_REFERENCE,
					assignment.getName()
					);
		} catch(RuntimeException exception) {
			
			String cycleMessage = findVariableCycleMessage(exception);
			
			if(cycleMessage != null) {
				error(exception.getMessage(),
						SephirahPackage.Literals.ASSIGNMENT__NAME,
						CYCLICAL_REFERENCE,
						assignment.getName()
						);
			}
			
			return;
		}
	}
	
	@Check
	public void checkDefinitionVariablesUsed(Definition def) {
		EList<Assignment> args = def.getArgs();
		Expression expr = def.getExpr();

		if (expr == null) {
			return;
		}

		for (Assignment arg : args) {
			if (arg instanceof DefinitionVariable) {
				DefinitionVariable definitionVariable = (DefinitionVariable) arg;
				String varName = definitionVariable.getName();

				if (varName == null || varName.isBlank()) {
					continue;
				}

				if (!expressionContainsVariableName(expr, varName)) {
					warning("Declared variable has not been used: " + varName,
							SephirahPackage.Literals.DEFINITION__ARGS,
							args.indexOf(arg),
							UNUSED_VARIABLE,
							varName);
				}
			}
		}
	}
	
	@Check
	public void checkDivByZero(Divide div) {
		BigDecimal divisor = tryComputeStatic(div.getRight());

		if (divisor == null) {
			return;
		}

		if (BigDecimal.ZERO.compareTo(divisor) == 0) {
			error("Cannot divide by zero.", SephirahPackage.Literals.DIVIDE__RIGHT);
		}
	}
	
	@Check
	public void checkDuplicateFunctions(Definition definition) {
		FormulaModel model = EcoreUtil2.getContainerOfType(definition, FormulaModel.class);
		
		if(model == null) {
			return;
		}
		
		String name = definition.getName();
		
		if(name == null || name.isBlank()) {
			return;
		}
		
		boolean foundFirst = false;
		
		for(Definition other : model.getMethodDefs()) {
			if(!name.equals(other.getName())) {
				continue;
			}
			
			if(!foundFirst) {
				foundFirst = true;
				continue;
			}
			
			if (other == definition) {
	            error("Function name " + name + " cannot be declared more than once.",
	                    SephirahPackage.Literals.DEFINITION__NAME,
	                    DUPLICATE_FUNCTION,
	                    name);
	            return;
	        }
		}
	}
	
	@Check
	public void checkDuplicateParameters(Definition definition) {
		EList<Assignment> parameters = definition.getArgs();
		
		Set<String> seenNames = new HashSet<>();
		
		for(int i = 0; i < parameters.size(); i++) {
			Assignment parameter = parameters.get(i);
			String name = parameter.getName();
			
			if(name == null || name.isBlank()) {
				continue;
			}
			
			if(!seenNames.add(name)) {
				error("Parameter name " + name + " cannot be used more than once.",
	                    SephirahPackage.Literals.DEFINITION__ARGS,
	                    i,
	                    DUPLICATE_PARAMETER,
	                    name);
	            return;
			}
		}
	}
	
	@Check
	public void checkDuplicateVariables(VariableAssignment variableAssignment) {
		FormulaModel model = EcoreUtil2.getContainerOfType(variableAssignment, FormulaModel.class);

		if (model == null) {
			return;
		}

		String name = variableAssignment.getName();

		if (name == null || name.isBlank()) {
			return;
		}

		boolean foundFirst = false;

		for (Assignment assignment : model.getVariables()) {
			if (!(assignment instanceof VariableAssignment)) {
				continue;
			}

			VariableAssignment other = (VariableAssignment) assignment;

			if (!name.equals(other.getName())) {
				continue;
			}

			if (!foundFirst) {
				foundFirst = true;
				continue;
			}

			if (other == variableAssignment) {
				error("Variable name " + name + " cannot be declared more than once.",
						SephirahPackage.Literals.ASSIGNMENT__NAME,
						DUPLICATE_VARIABLE,
						name,
						sourceText(variableAssignment.getValue()));
				return;
			}
		}
	}
	
	@Check
	public void checkEvaluationResult(Evaluation evaluation) {
		FormulaModel model = EcoreUtil2.getContainerOfType(evaluation, FormulaModel.class);
		
		if(model == null || evaluation.getExpression() == null) {
			return;
		}
		
		try {
		ModuleEvaluator evaluator = new ModuleEvaluator(model, Methods.previewRegistry());
		SephirahValue result = evaluator.evaluateValue(evaluation.getExpression());
		
		info("Result: " + result,
				SephirahPackage.Literals.EVALUATION__EXPRESSION,
				EVALUATION_RESULT,
				result.toString());
		} catch(RuntimeException exception) {
			return;
		}
	}
	
	@Check
	public void checkExistingVariable(Variable var) {
		String name = var.getName();

		if (name == null || name.isBlank()) {
			error("Variable has no name.",
					SephirahPackage.Literals.VARIABLE__NAME,
					UNDECLARED_VARIABLE);
			return;
		}

		/*
		 * Qualified names are reserved for runtime/host-object paths for now:
		 *
		 *   self.strength
		 *   weapon.damage
		 *   target.armorClass
		 *
		 * These should not be forced to resolve as module-local variables.
		 */
		if (name.contains(".")) {
			return;
		}

		if (isVariableDeclared(var, name)) {
			return;
		}

		error("Variable has not been declared: " + name,
				SephirahPackage.Literals.VARIABLE__NAME,
				UNDECLARED_VARIABLE,
				name);
	}
	
	@Check
	public void checkFunctionArity(MethodCall methodCall) {
		String name = methodCall.getName();
		
		if(name == null || name.isBlank()) {
			return;
		}
		
		FunctionSignature signature = getFunctionSignature(methodCall, name);
		
		if(signature == null) {
			return;
		}
	    
		int actual = methodCall.getArgs().size();
		
		if(signature.accepts(actual)) {
			return;
		}
		
	    error(signature.describeMismatch(name, actual),
        SephirahPackage.Literals.METHOD_CALL__NAME,
        FUNCTION_ARITY,
        name,
        String.valueOf(actual));
	}

	@Check
	public void checkKnownFunction(MethodCall methodCall) {
		String name = methodCall.getName();
		
		if (name == null || name.isBlank()) {
	        error("Function call has no name.",
	                SephirahPackage.Literals.METHOD_CALL__NAME,
	                UNKNOWN_FUNCTION);
	        return;
	    }
		
		if(isKnownFunction(methodCall, name)) {
			return;
		}
		
		error("Unknown function: " + name,
	            SephirahPackage.Literals.METHOD_CALL__NAME,
	            UNKNOWN_FUNCTION,
	            name);
	}

	@Check
	public void checkNormalizable(Expression expr) {
		if (expr instanceof NumberLiteral || expr instanceof MethodCall || expr instanceof Variable) {
			return;
		}

		Evaluation eval = EcoreUtil2.getContainerOfType(expr, Evaluation.class);

		if (eval != null) {
			return;
		}
		
		if (hasNormalizableExpressionParent(expr)) {
		    return;
		}

		if (!isStaticNumericExpression(expr)) {
			return;
		}
		
		if(isSimpleNegativeLiteral(expr)) {
			return;
		}

		BigDecimal decimal = tryComputeStatic(expr);

		if (decimal == null) {
			return;
		}

		if (decimal.toString().length() <= 8) {
			info("Expression could be normalized to constant '" + decimal + "'",
					null,
					ValidationMessageAcceptor.INSIGNIFICANT_INDEX,
					NORMALIZABLE,
					decimal.toString());
		}
	}

	@Check
	public void checkVariableUsed(VariableAssignment assignment) {
		String name = assignment.getName();

		if (name == null || name.isBlank()) {
			return;
		}

		FormulaModel model = EcoreUtil2.getContainerOfType(assignment, FormulaModel.class);

		if (model == null) {
			return;
		}

		if (isVariableUsedInModel(model, assignment, name)) {
			return;
		}

		info("Declared variable has not been used.",
				SephirahPackage.Literals.ASSIGNMENT__NAME,
				UNUSED_VARIABLE,
				name);
	}

	private static void checkFunctionCycle(
			FormulaModel model,
			String functionName,
			Deque<String> stack) {
		
		if (stack.contains(functionName)) {
	        throw new IllegalStateException("Cyclic function definition: "
	                + formatFunctionCycle(functionName, stack));
	    }
		
		Definition definition = findDefinition(model, functionName);
		
		if(definition == null || definition.getExpr() == null) {
			return;
		}
		
		stack.push(functionName);
		
		try {
			for(String calledFunction : findCalledFunctionName(definition.getExpr())) {
				if(isModuleFunction(model, calledFunction)) {
					checkFunctionCycle(model, calledFunction, stack);
				}
			}
		} finally {
			stack.pop();
		}
	}

	private static boolean expressionContainsVariableName(Expression expression, String name) {
		if (expression == null) {
			return false;
		}

		if (expression instanceof Variable) {
			Variable variable = (Variable) expression;
			return name.equals(variable.getName());
		}

		TreeIterator<EObject> contents = expression.eAllContents();

		while (contents.hasNext()) {
			EObject object = contents.next();

			if (object instanceof Variable) {
				Variable variable = (Variable) object;

				if (name.equals(variable.getName())) {
					return true;
				}
			}
		}

		return false;
	}
	
	private static FunctionSignature getFunctionSignature(EObject object, String name) {
		FunctionSignature builtInSignature =
				Methods.standardRegistry().getSignature(name);
		
		if(builtInSignature != null) {
			return builtInSignature;
		}
		
		FormulaModel model = EcoreUtil2.getContainerOfType(object, FormulaModel.class);
		
		if(model == null) {
			return null;
		}
		
		Definition definition = findDefinition(model, name);
		
		if(definition == null) {
			return null;
		}
		
		return FunctionSignature.exactly(definition.getArgs().size());
	}
	
	private static Set<String> findCalledFunctionName(Expression expression){
		Set<String> names = new HashSet<>();
		
		if(expression == null) {
			return names;
		}
		
		if(expression instanceof MethodCall) {
			MethodCall methodCall = (MethodCall) expression;
			
			if(methodCall.getName() != null && !methodCall.getName().isBlank()) {
				names.add(methodCall.getName());
			}
		}
		
		TreeIterator<EObject> contents = expression.eAllContents();
		
		while(contents.hasNext()) {
			EObject object = contents.next();
			
			if(object instanceof MethodCall) {
				MethodCall methodCall = (MethodCall) object;
				
				if(methodCall.getName() != null && !methodCall.getName().isBlank()) {
					names.add(methodCall.getName());
				}
			}
		}
		
		return names;
	}
	
	private static Definition findDefinition(FormulaModel model, String name) {
		for(Definition definition : model.getMethodDefs()) {
			if(name.equals(definition.getName())) {
				return definition;
			}
		}
		
		return null;
	}

	private static String findVariableCycleMessage(Throwable throwable) {
	    Throwable current = throwable;

	    while (current != null) {
	        String message = current.getMessage();

	        if (message != null && message.startsWith("Cyclic variable definition:")) {
	            return message;
	        }

	        current = current.getCause();
	    }

	    return null;
	}
	
	private static String formatFunctionCycle(String repeatedName, Deque<String> stack) {
		List<String> path = new ArrayList<String>(stack);
		Collections.reverse(path);
		
		int cycleStart = path.indexOf(repeatedName);
		
		StringBuilder builder = new StringBuilder();
		
		if(cycleStart >= 0) {
			for(int i = cycleStart; i < path.size(); i++) {
				if(builder.length() > 0) {
					builder.append(" -> ");
				}
				
				builder.append(path.get(i));
			}
			
			builder.append(" -> ").append(repeatedName);
			
			return builder.toString();
		}
		
		builder.append(repeatedName);
		
		for(String name : path) {
			builder.append(" -> ").append(name);
		}
		
		builder.append(" -> ").append(repeatedName);
		
		return builder.toString();
	}
	
	private static boolean hasNormalizableExpressionParent(Expression expr) {
	    EObject container = expr.eContainer();

	    while (container != null) {
	        if (container instanceof Expression parentExpression) {
	            return isStaticNumericExpression(parentExpression)
	                    && !isSimpleNegativeLiteral(parentExpression);
	        }

	        container = container.eContainer();
	    }

	    return false;
	}
	
	private static boolean isKnownFunction(MethodCall methodCall, String name) {
		if(Methods.standardRegistry().contains(name)) {
			return true;
		}
		
		FormulaModel model = EcoreUtil2.getContainerOfType(methodCall, FormulaModel.class);
		
		if(model == null) {
			return false;
		}
		
		for(Definition definition : model.getMethodDefs()) {
			if(definition.getName().equals(name)) {
				return true;
			}
		}
		
		return false;
	}
	
	private static boolean isModuleFunction(FormulaModel model, String name) {
		return findDefinition(model, name) != null;
	}
	
	private static boolean isSimpleNegativeLiteral(Expression expression) {
	    if (expression instanceof Negate negate) {
	        return negate.getValue() instanceof NumberLiteral;
	    }

	    return false;
	}
	
	private static boolean isStaticCondition(Condition condition) {
		if(condition == null) {
			return false;
		}
		
		if(condition instanceof ComparisonCondition comparisonCondition) {
			return isStaticNumericExpression(comparisonCondition.getLeft())
					&& isStaticNumericExpression(comparisonCondition.getRight())
					&& comparisonCondition.getOp() != null;
		}
		
		if(condition instanceof AndCondition andCondition) {
			return isStaticCondition(andCondition.getLeft())
					&& isStaticCondition(andCondition.getRight());
		}
		
		if(condition instanceof OrCondition orCondition) {
			return isStaticCondition(orCondition.getLeft())
					|| isStaticCondition(orCondition.getRight());
		}
		
		if(condition instanceof NotCondition notCondition) {
			return isStaticCondition(notCondition.getCondition());
		}
		
		return false;
	}
	
	private static boolean isStaticNumericExpression(Expression expression) {
		if(expression == null) {
			return false;
		}

		if(expression instanceof NumberLiteral || expression instanceof Constant) {
			return true;
		}

		if(expression instanceof Variable || expression instanceof MethodCall) {
			return false;
		}

		if(expression instanceof Add add) {
			return isStaticNumericExpression(add.getLeft())
					&& isStaticNumericExpression(add.getRight());
		}

		if(expression instanceof Subtract subtract) {
			return isStaticNumericExpression(subtract.getLeft())
					&& isStaticNumericExpression(subtract.getRight());
		}

		if(expression instanceof Multiply multiply) {
			return isStaticNumericExpression(multiply.getLeft())
					&& isStaticNumericExpression(multiply.getRight());
		}

		if(expression instanceof Divide divide) {
			return isStaticNumericExpression(divide.getLeft())
					&& isStaticNumericExpression(divide.getRight());
		}

		if(expression instanceof Exponent exponent) {
			return isStaticNumericExpression(exponent.getLeft())
					&& isStaticNumericExpression(exponent.getRight());
		}
		
		if(expression instanceof Conditional conditional) {
			return isStaticCondition(conditional.getCondition())
					&& isStaticNumericExpression(conditional.getThenBranch())
					&& isStaticNumericExpression(conditional.getElseBranch());
		}
		
		if(expression instanceof Negate negate) {
			return isStaticNumericExpression(negate.getValue());
		}

		return false;
	}

	private static boolean isVariableDeclared(Variable variable, String name) {
		Definition definition = EcoreUtil2.getContainerOfType(variable, Definition.class);

	    if (definition != null) {
	        for (Assignment arg : definition.getArgs()) {
	            if (name.equals(arg.getName())) {
	                return true;
	            }
	        }
	    }

	    FormulaModel model = EcoreUtil2.getContainerOfType(variable, FormulaModel.class);

	    if (model != null) {
	        for (Assignment assignment : model.getVariables()) {
	            if (name.equals(assignment.getName())) {
	                return true;
	            }
	        }
	    }

	    return false;
	}

	private static boolean isVariableUsedInModel(
			FormulaModel model,
			VariableAssignment declaration,
			String name) {

		for (Assignment assignment : model.getVariables()) {
			if (!(assignment instanceof VariableAssignment)) {
				continue;
			}

			VariableAssignment variableAssignment = (VariableAssignment) assignment;

			if (variableAssignment == declaration) {
				continue;
			}

			if (expressionContainsVariableName(variableAssignment.getValue(), name)) {
				return true;
			}
		}

		for (Definition definition : model.getMethodDefs()) {
			if (expressionContainsVariableName(definition.getExpr(), name)) {
				return true;
			}
		}

		for (Evaluation evaluation : model.getValues()) {
			if (expressionContainsVariableName(evaluation.getExpression(), name)) {
				return true;
			}
		}

		return false;
	}
	
	private static String sourceText(EObject object) {
		if (object == null) {
			return "";
		}

		ICompositeNode node = NodeModelUtils.findActualNodeFor(object);

		if (node == null) {
			return "";
		}

		return node.getText();
	}

	private static BigDecimal tryComputeStatic(Expression expression) {
		if (!isStaticNumericExpression(expression)) {
			return null;
		}

		try {
			return Computer.compute(expression);
		} catch (RuntimeException exception) {
			return null;
		}
	}
}
