/*
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.validation;

import java.math.BigDecimal;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.nodemodel.ICompositeNode;
import org.eclipse.xtext.nodemodel.util.NodeModelUtils;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.ValidationMessageAcceptor;

import com.fearlesstyrant.sephirah.sephirah.*;
import com.fearlesstyrant.sephirah.tools.*;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SephirahValidator extends AbstractSephirahValidator {

	public static final String CODE_PREFIX = "com.fearlesstyrant.sephirah.";
	public static final String NORMALIZABLE = CODE_PREFIX + "normalizable_expression";
	public static final String UNDECLARED_VARIABLE = CODE_PREFIX + "undeclared_variable";
	public static final String UNUSED_VARIABLE = CODE_PREFIX + "unused_variable";
	public static final String DUPLICATE_VARIABLE = CODE_PREFIX + "duplicate_variable";
	public static final String NO_VARIABLE = CODE_PREFIX + "no_variable";
	public static final String EVALUATION_RESULT = CODE_PREFIX + "evaluation_result";
	public static final String CYCLICAL_REFERENCE = CODE_PREFIX + "cyclical_reference";
	public static final String DUPLICATE_FUNCTION = CODE_PREFIX + "duplicate_function";
	public static final String BUILTIN_FUNCTION_CONFLICT = CODE_PREFIX + "builtin_function_conflict";

	@Check
	public void checkBuiltinFunctionConflict(Definition definition) {
		String name = definition.getName();
		
		if(name == null || name.isBlank()) {
			return;
		}
		
		if (Methods.previewRegistry().contains(name) || Methods.standardRegistry().contains(name)) {
	        error("Function name " + name + " conflicts with a built-in function.",
	                SephirahPackage.Literals.DEFINITION__NAME,
	                BUILTIN_FUNCTION_CONFLICT,
	                name);
	    }
	}
	
	@Check
	public void checkCyclicalVariableReference(VariableAssignment assignment) {
		FormulaModel model = EcoreUtil2.getContainerOfType(assignment, FormulaModel.class);
		
		if(model == null || assignment.getName() == null || assignment.getValue() == null) {
			return;
		}
		
		try {
			ModuleValueResolver resolver = new ModuleValueResolver(model, 
					Methods.previewRegistry());
			
			resolver.resolveValue(assignment.getName());
		} catch(IllegalStateException exception) {
			error(exception.getMessage(),
					SephirahPackage.Literals.ASSIGNMENT__NAME,
					CYCLICAL_REFERENCE,
					assignment.getName()
					);
		} catch(RuntimeException exception) {
			return;
		}
	}
	@Check
	public void checkDivByZero(Divide div) {
		BigDecimal divisor = tryComputeStatic(div.getRight());

		if (divisor == null) {
			return;
		}

		if (BigDecimal.ZERO.compareTo(divisor) == 0) {
			error("Cannot divide by zero.", SephirahPackage.Literals.DIVIDE__RIGHT);
		}
	}
	
	@Check
	public void checkDuplicateFunctions(Definition definition) {
		FormulaModel model = EcoreUtil2.getContainerOfType(definition, FormulaModel.class);
		
		if(model == null) {
			return;
		}
		
		String name = definition.getName();
		
		if(name == null || name.isBlank()) {
			return;
		}
		
		boolean foundFirst = false;
		
		for(Definition other : model.getMethodDefs()) {
			if(!name.equals(other.getName())) {
				continue;
			}
			
			if(!foundFirst) {
				foundFirst = true;
				continue;
			}
			
			if (other == definition) {
	            error("Function name " + name + " cannot be declared more than once.",
	                    SephirahPackage.Literals.DEFINITION__NAME,
	                    DUPLICATE_FUNCTION,
	                    name);
	            return;
	        }
		}
	}
	
	@Check
	public void checkEvaluationResult(Evaluation evaluation) {
		FormulaModel model = EcoreUtil2.getContainerOfType(evaluation, FormulaModel.class);
		
		if(model == null || evaluation.getExpression() == null) {
			return;
		}
		
		try {
		ModuleEvaluator evaluator = new ModuleEvaluator(model, Methods.previewRegistry());
		BigDecimal result = evaluator.evaluate(evaluation);
		
		info("Result: " + result,
				SephirahPackage.Literals.EVALUATION__EXPRESSION,
				EVALUATION_RESULT,
				result.toString());
		} catch(RuntimeException exception) {
			return;
		}
	}

	@Check
	public void checkNormalizable(Expression expr) {
		if (expr instanceof NumberLiteral || expr instanceof MethodCall || expr instanceof Variable) {
			return;
		}

		Evaluation eval = EcoreUtil2.getContainerOfType(expr, Evaluation.class);

		if (eval != null) {
			return;
		}

		if (!isStaticNumericExpression(expr)) {
			return;
		}

		BigDecimal decimal = tryComputeStatic(expr);

		if (decimal == null) {
			return;
		}

		if (decimal.toString().length() <= 8) {
			warning("Expression could be normalized to constant '" + decimal + "'",
					null,
					ValidationMessageAcceptor.INSIGNIFICANT_INDEX,
					NORMALIZABLE,
					decimal.toString());
		}
	}

	@Check
	public void checkExistingVariable(Variable var) {
		String name = var.getName();

		if (name == null || name.isBlank()) {
			error("Variable has no name.",
					SephirahPackage.Literals.VARIABLE__NAME,
					UNDECLARED_VARIABLE);
			return;
		}

		/*
		 * Qualified names are reserved for runtime/host-object paths for now:
		 *
		 *   self.strength
		 *   weapon.damage
		 *   target.armorClass
		 *
		 * These should not be forced to resolve as module-local variables.
		 */
		if (name.contains(".")) {
			return;
		}

		if (isVariableDeclared(var, name)) {
			return;
		}

		error("Variable has not been declared: " + name,
				SephirahPackage.Literals.VARIABLE__NAME,
				UNDECLARED_VARIABLE,
				name);
	}

	@Check
	public void checkVariableUsed(VariableAssignment assignment) {
		String name = assignment.getName();

		if (name == null || name.isBlank()) {
			return;
		}

		FormulaModel model = EcoreUtil2.getContainerOfType(assignment, FormulaModel.class);

		if (model == null) {
			return;
		}

		if (isVariableUsedInModel(model, assignment, name)) {
			return;
		}

		info("Declared variable has not been used.",
				SephirahPackage.Literals.ASSIGNMENT__NAME,
				UNUSED_VARIABLE,
				name);
	}

	@Check
	public void checkDefinitionVariablesUsed(Definition def) {
		EList<Assignment> args = def.getArgs();
		Expression expr = def.getExpr();

		if (expr == null) {
			return;
		}

		for (Assignment arg : args) {
			if (arg instanceof DefinitionVariable) {
				DefinitionVariable definitionVariable = (DefinitionVariable) arg;
				String varName = definitionVariable.getName();

				if (varName == null || varName.isBlank()) {
					continue;
				}

				if (!expressionContainsVariableName(expr, varName)) {
					warning("Declared variable has not been used: " + varName,
							SephirahPackage.Literals.DEFINITION__ARGS,
							args.indexOf(arg),
							UNUSED_VARIABLE,
							varName);
				}
			}
		}
	}

	@Check
	public void checkForDuplicateVariables(VariableAssignment variableAssignment) {
		FormulaModel model = EcoreUtil2.getContainerOfType(variableAssignment, FormulaModel.class);

		if (model == null) {
			return;
		}

		String name = variableAssignment.getName();

		if (name == null || name.isBlank()) {
			return;
		}

		boolean foundFirst = false;

		for (Assignment assignment : model.getVariables()) {
			if (!(assignment instanceof VariableAssignment)) {
				continue;
			}

			VariableAssignment other = (VariableAssignment) assignment;

			if (!name.equals(other.getName())) {
				continue;
			}

			if (!foundFirst) {
				foundFirst = true;
				continue;
			}

			if (other == variableAssignment) {
				error("Variable name " + name + " cannot be declared more than once.",
						SephirahPackage.Literals.ASSIGNMENT__NAME,
						DUPLICATE_VARIABLE,
						name,
						sourceText(variableAssignment.getValue()));
				return;
			}
		}
	}

	private static boolean isVariableDeclared(Variable variable, String name) {
		Definition definition = EcoreUtil2.getContainerOfType(variable, Definition.class);

		if (definition != null) {
			for (Assignment arg : definition.getArgs()) {
				if (name.equals(arg.getName())) {
					return true;
				}
			}
		}

		FormulaModel model = EcoreUtil2.getContainerOfType(variable, FormulaModel.class);

		if (model != null) {
			for (Assignment assignment : model.getVariables()) {
				if (name.equals(assignment.getName())) {
					return true;
				}
			}
		}

		return false;
	}

	private static boolean isVariableUsedInModel(
			FormulaModel model,
			VariableAssignment declaration,
			String name) {

		for (Assignment assignment : model.getVariables()) {
			if (!(assignment instanceof VariableAssignment)) {
				continue;
			}

			VariableAssignment variableAssignment = (VariableAssignment) assignment;

			if (variableAssignment == declaration) {
				continue;
			}

			if (expressionContainsVariableName(variableAssignment.getValue(), name)) {
				return true;
			}
		}

		for (Definition definition : model.getMethodDefs()) {
			if (expressionContainsVariableName(definition.getExpr(), name)) {
				return true;
			}
		}

		for (Evaluation evaluation : model.getValues()) {
			if (expressionContainsVariableName(evaluation.getExpression(), name)) {
				return true;
			}
		}

		return false;
	}

	private static boolean expressionContainsVariableName(Expression expression, String name) {
		if (expression == null) {
			return false;
		}

		if (expression instanceof Variable) {
			Variable variable = (Variable) expression;
			return name.equals(variable.getName());
		}

		TreeIterator<EObject> contents = expression.eAllContents();

		while (contents.hasNext()) {
			EObject object = contents.next();

			if (object instanceof Variable) {
				Variable variable = (Variable) object;

				if (name.equals(variable.getName())) {
					return true;
				}
			}
		}

		return false;
	}

	private static BigDecimal tryComputeStatic(Expression expression) {
		if (!isStaticNumericExpression(expression)) {
			return null;
		}

		try {
			return Computer.compute(expression);
		} catch (RuntimeException exception) {
			return null;
		}
	}

	private static boolean isStaticNumericExpression(Expression expression) {
		if (expression == null) {
			return false;
		}

		if (expression instanceof NumberLiteral || expression instanceof Constant) {
			return true;
		}

		if (expression instanceof Variable || expression instanceof MethodCall) {
			return false;
		}

		if (expression instanceof Add) {
			Add add = (Add) expression;
			return isStaticNumericExpression(add.getLeft())
					&& isStaticNumericExpression(add.getRight());
		}

		if (expression instanceof Subtract) {
			Subtract subtract = (Subtract) expression;
			return isStaticNumericExpression(subtract.getLeft())
					&& isStaticNumericExpression(subtract.getRight());
		}

		if (expression instanceof Multiply) {
			Multiply multiply = (Multiply) expression;
			return isStaticNumericExpression(multiply.getLeft())
					&& isStaticNumericExpression(multiply.getRight());
		}

		if (expression instanceof Divide) {
			Divide divide = (Divide) expression;
			return isStaticNumericExpression(divide.getLeft())
					&& isStaticNumericExpression(divide.getRight());
		}

		if (expression instanceof Exponent) {
			Exponent exponent = (Exponent) expression;
			return isStaticNumericExpression(exponent.getLeft())
					&& isStaticNumericExpression(exponent.getRight());
		}

		return false;
	}

	private static String sourceText(EObject object) {
		if (object == null) {
			return "";
		}

		ICompositeNode node = NodeModelUtils.findActualNodeFor(object);

		if (node == null) {
			return "";
		}

		return node.getText();
	}
	
}
