/**
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.sephirah;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparison Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getLeft <em>Left</em>}</li>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getOp <em>Op</em>}</li>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getComparisonCondition()
 * @model
 * @generated
 */
public interface ComparisonCondition extends Condition
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Expression)
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getComparisonCondition_Left()
   * @model containment="true"
   * @generated
   */
  Expression getLeft();

  /**
   * Sets the value of the '{@link com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Expression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * The literals are from the enumeration {@link com.fearlesstyrant.sephirah.sephirah.ComparisonOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see com.fearlesstyrant.sephirah.sephirah.ComparisonOperator
   * @see #setOp(ComparisonOperator)
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getComparisonCondition_Op()
   * @model
   * @generated
   */
  ComparisonOperator getOp();

  /**
   * Sets the value of the '{@link com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see com.fearlesstyrant.sephirah.sephirah.ComparisonOperator
   * @see #getOp()
   * @generated
   */
  void setOp(ComparisonOperator value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Expression)
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getComparisonCondition_Right()
   * @model containment="true"
   * @generated
   */
  Expression getRight();

  /**
   * Sets the value of the '{@link com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Expression value);

} // ComparisonCondition
