/**
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.sephirah;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.Conditional#getCondition <em>Condition</em>}</li>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.Conditional#getThenBranch <em>Then Branch</em>}</li>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.Conditional#getElseBranch <em>Else Branch</em>}</li>
 * </ul>
 *
 * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getConditional()
 * @model
 * @generated
 */
public interface Conditional extends Expression
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Condition)
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getConditional_Condition()
   * @model containment="true"
   * @generated
   */
  Condition getCondition();

  /**
   * Sets the value of the '{@link com.fearlesstyrant.sephirah.sephirah.Conditional#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Condition value);

  /**
   * Returns the value of the '<em><b>Then Branch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Branch</em>' containment reference.
   * @see #setThenBranch(Expression)
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getConditional_ThenBranch()
   * @model containment="true"
   * @generated
   */
  Expression getThenBranch();

  /**
   * Sets the value of the '{@link com.fearlesstyrant.sephirah.sephirah.Conditional#getThenBranch <em>Then Branch</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Branch</em>' containment reference.
   * @see #getThenBranch()
   * @generated
   */
  void setThenBranch(Expression value);

  /**
   * Returns the value of the '<em><b>Else Branch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Branch</em>' containment reference.
   * @see #setElseBranch(Expression)
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getConditional_ElseBranch()
   * @model containment="true"
   * @generated
   */
  Expression getElseBranch();

  /**
   * Sets the value of the '{@link com.fearlesstyrant.sephirah.sephirah.Conditional#getElseBranch <em>Else Branch</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else Branch</em>' containment reference.
   * @see #getElseBranch()
   * @generated
   */
  void setElseBranch(Expression value);

} // Conditional
