/**
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.sephirah;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
} // Condition
