/**
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.sephirah;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formula Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel#getName <em>Name</em>}</li>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel#getImports <em>Imports</em>}</li>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel#getMethodDefs <em>Method Defs</em>}</li>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel#getVariables <em>Variables</em>}</li>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getFormulaModel()
 * @model
 * @generated
 */
public interface FormulaModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(DocName)
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getFormulaModel_Name()
   * @model containment="true"
   * @generated
   */
  DocName getName();

  /**
   * Sets the value of the '{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(DocName value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link com.fearlesstyrant.sephirah.sephirah.Import}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getFormulaModel_Imports()
   * @model containment="true"
   * @generated
   */
  EList<Import> getImports();

  /**
   * Returns the value of the '<em><b>Method Defs</b></em>' containment reference list.
   * The list contents are of type {@link com.fearlesstyrant.sephirah.sephirah.Definition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method Defs</em>' containment reference list.
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getFormulaModel_MethodDefs()
   * @model containment="true"
   * @generated
   */
  EList<Definition> getMethodDefs();

  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link com.fearlesstyrant.sephirah.sephirah.Assignment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getFormulaModel_Variables()
   * @model containment="true"
   * @generated
   */
  EList<Assignment> getVariables();

  /**
   * Returns the value of the '<em><b>Values</b></em>' containment reference list.
   * The list contents are of type {@link com.fearlesstyrant.sephirah.sephirah.Evaluation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' containment reference list.
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getFormulaModel_Values()
   * @model containment="true"
   * @generated
   */
  EList<Evaluation> getValues();

} // FormulaModel
