/**
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.sephirah;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Import</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.Import#getModule <em>Module</em>}</li>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.Import#getAlias <em>Alias</em>}</li>
 * </ul>
 *
 * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getImport()
 * @model
 * @generated
 */
public interface Import extends EObject
{
  /**
   * Returns the value of the '<em><b>Module</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Module</em>' attribute.
   * @see #setModule(String)
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getImport_Module()
   * @model
   * @generated
   */
  String getModule();

  /**
   * Sets the value of the '{@link com.fearlesstyrant.sephirah.sephirah.Import#getModule <em>Module</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Module</em>' attribute.
   * @see #getModule()
   * @generated
   */
  void setModule(String value);

  /**
   * Returns the value of the '<em><b>Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' attribute.
   * @see #setAlias(String)
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getImport_Alias()
   * @model
   * @generated
   */
  String getAlias();

  /**
   * Sets the value of the '{@link com.fearlesstyrant.sephirah.sephirah.Import#getAlias <em>Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias</em>' attribute.
   * @see #getAlias()
   * @generated
   */
  void setAlias(String value);

} // Import
