/**
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.sephirah;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.MethodCall#getName <em>Name</em>}</li>
 *   <li>{@link com.fearlesstyrant.sephirah.sephirah.MethodCall#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getMethodCall()
 * @model
 * @generated
 */
public interface MethodCall extends Expression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getMethodCall_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.fearlesstyrant.sephirah.sephirah.MethodCall#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link com.fearlesstyrant.sephirah.sephirah.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see com.fearlesstyrant.sephirah.sephirah.SephirahPackage#getMethodCall_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArgs();

} // MethodCall
