/**
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.sephirah;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.fearlesstyrant.sephirah.sephirah.SephirahFactory
 * @model kind="package"
 * @generated
 */
public interface SephirahPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "sephirah";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.fearlesstyrant.com/sephirah/Sephirah";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "sephirah";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SephirahPackage eINSTANCE = com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl.init();

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.FormulaModelImpl <em>Formula Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.FormulaModelImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getFormulaModel()
   * @generated
   */
  int FORMULA_MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_MODEL__IMPORTS = 1;

  /**
   * The feature id for the '<em><b>Method Defs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_MODEL__METHOD_DEFS = 2;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_MODEL__VARIABLES = 3;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_MODEL__VALUES = 4;

  /**
   * The number of structural features of the '<em>Formula Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_MODEL_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.DocNameImpl <em>Doc Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.DocNameImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getDocName()
   * @generated
   */
  int DOC_NAME = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOC_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Doc Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOC_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.ImportImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__NAME = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.StatementImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 3;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.DefinitionImpl <em>Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.DefinitionImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getDefinition()
   * @generated
   */
  int DEFINITION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__ARGS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__EXPR = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.AssignmentImpl <em>Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.AssignmentImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getAssignment()
   * @generated
   */
  int ASSIGNMENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.ExpressionImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 8;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.VariableImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.EvaluationImpl <em>Evaluation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.EvaluationImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getEvaluation()
   * @generated
   */
  int EVALUATION = 7;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVALUATION__EXPRESSION = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Evaluation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVALUATION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.ConditionImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 9;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ConstantImpl <em>Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.ConstantImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getConstant()
   * @generated
   */
  int CONSTANT = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.VariableAssignmentImpl <em>Variable Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.VariableAssignmentImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getVariableAssignment()
   * @generated
   */
  int VARIABLE_ASSIGNMENT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ASSIGNMENT__NAME = ASSIGNMENT__NAME;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ASSIGNMENT__VALUE = ASSIGNMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ASSIGNMENT_FEATURE_COUNT = ASSIGNMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.DefinitionVariableImpl <em>Definition Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.DefinitionVariableImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getDefinitionVariable()
   * @generated
   */
  int DEFINITION_VARIABLE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION_VARIABLE__NAME = ASSIGNMENT__NAME;

  /**
   * The number of structural features of the '<em>Definition Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION_VARIABLE_FEATURE_COUNT = ASSIGNMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ConditionalImpl <em>Conditional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.ConditionalImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getConditional()
   * @generated
   */
  int CONDITIONAL = 13;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__CONDITION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then Branch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__THEN_BRANCH = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else Branch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__ELSE_BRANCH = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Conditional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.AddImpl <em>Add</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.AddImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getAdd()
   * @generated
   */
  int ADD = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Add</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.SubtractImpl <em>Subtract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SubtractImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getSubtract()
   * @generated
   */
  int SUBTRACT = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Subtract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTRACT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.MultiplyImpl <em>Multiply</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.MultiplyImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getMultiply()
   * @generated
   */
  int MULTIPLY = 16;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLY__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLY__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Multiply</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLY_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.DivideImpl <em>Divide</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.DivideImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getDivide()
   * @generated
   */
  int DIVIDE = 17;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Divide</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.NegateImpl <em>Negate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.NegateImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getNegate()
   * @generated
   */
  int NEGATE = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATE__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Negate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ExponentImpl <em>Exponent</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.ExponentImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getExponent()
   * @generated
   */
  int EXPONENT = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPONENT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPONENT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Exponent</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPONENT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.NumberLiteralImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getNumberLiteral()
   * @generated
   */
  int NUMBER_LITERAL = 20;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.OrConditionImpl <em>Or Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.OrConditionImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getOrCondition()
   * @generated
   */
  int OR_CONDITION = 21;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CONDITION__LEFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CONDITION__RIGHT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.AndConditionImpl <em>And Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.AndConditionImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getAndCondition()
   * @generated
   */
  int AND_CONDITION = 22;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CONDITION__LEFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CONDITION__RIGHT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.NotConditionImpl <em>Not Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.NotConditionImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getNotCondition()
   * @generated
   */
  int NOT_CONDITION = 23;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_CONDITION__CONDITION = CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ComparisonConditionImpl <em>Comparison Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.ComparisonConditionImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getComparisonCondition()
   * @generated
   */
  int COMPARISON_CONDITION = 24;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_CONDITION__LEFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_CONDITION__OP = CONDITION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_CONDITION__RIGHT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Comparison Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.MethodCallImpl <em>Method Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.impl.MethodCallImpl
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getMethodCall()
   * @generated
   */
  int METHOD_CALL = 25;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_CALL__NAME = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_CALL__ARGS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Method Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_CALL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.fearlesstyrant.sephirah.sephirah.ComparisonOperator <em>Comparison Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.fearlesstyrant.sephirah.sephirah.ComparisonOperator
   * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getComparisonOperator()
   * @generated
   */
  int COMPARISON_OPERATOR = 26;


  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel <em>Formula Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formula Model</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.FormulaModel
   * @generated
   */
  EClass getFormulaModel();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.FormulaModel#getName()
   * @see #getFormulaModel()
   * @generated
   */
  EReference getFormulaModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.FormulaModel#getImports()
   * @see #getFormulaModel()
   * @generated
   */
  EReference getFormulaModel_Imports();

  /**
   * Returns the meta object for the containment reference list '{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel#getMethodDefs <em>Method Defs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Method Defs</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.FormulaModel#getMethodDefs()
   * @see #getFormulaModel()
   * @generated
   */
  EReference getFormulaModel_MethodDefs();

  /**
   * Returns the meta object for the containment reference list '{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.FormulaModel#getVariables()
   * @see #getFormulaModel()
   * @generated
   */
  EReference getFormulaModel_Variables();

  /**
   * Returns the meta object for the containment reference list '{@link com.fearlesstyrant.sephirah.sephirah.FormulaModel#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.FormulaModel#getValues()
   * @see #getFormulaModel()
   * @generated
   */
  EReference getFormulaModel_Values();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.DocName <em>Doc Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Doc Name</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.DocName
   * @generated
   */
  EClass getDocName();

  /**
   * Returns the meta object for the attribute '{@link com.fearlesstyrant.sephirah.sephirah.DocName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.DocName#getName()
   * @see #getDocName()
   * @generated
   */
  EAttribute getDocName_Name();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link com.fearlesstyrant.sephirah.sephirah.Import#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Import#getName()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_Name();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Definition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Definition</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Definition
   * @generated
   */
  EClass getDefinition();

  /**
   * Returns the meta object for the attribute '{@link com.fearlesstyrant.sephirah.sephirah.Definition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Definition#getName()
   * @see #getDefinition()
   * @generated
   */
  EAttribute getDefinition_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.fearlesstyrant.sephirah.sephirah.Definition#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Definition#getArgs()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_Args();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Definition#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Definition#getExpr()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_Expr();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Assignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Assignment
   * @generated
   */
  EClass getAssignment();

  /**
   * Returns the meta object for the attribute '{@link com.fearlesstyrant.sephirah.sephirah.Assignment#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Assignment#getName()
   * @see #getAssignment()
   * @generated
   */
  EAttribute getAssignment_Name();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link com.fearlesstyrant.sephirah.sephirah.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Evaluation <em>Evaluation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evaluation</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Evaluation
   * @generated
   */
  EClass getEvaluation();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Evaluation#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Evaluation#getExpression()
   * @see #getEvaluation()
   * @generated
   */
  EReference getEvaluation_Expression();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Constant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constant</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Constant
   * @generated
   */
  EClass getConstant();

  /**
   * Returns the meta object for the attribute '{@link com.fearlesstyrant.sephirah.sephirah.Constant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Constant#getValue()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_Value();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.VariableAssignment <em>Variable Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Assignment</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.VariableAssignment
   * @generated
   */
  EClass getVariableAssignment();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.VariableAssignment#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.VariableAssignment#getValue()
   * @see #getVariableAssignment()
   * @generated
   */
  EReference getVariableAssignment_Value();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.DefinitionVariable <em>Definition Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Definition Variable</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.DefinitionVariable
   * @generated
   */
  EClass getDefinitionVariable();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Conditional <em>Conditional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditional</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Conditional
   * @generated
   */
  EClass getConditional();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Conditional#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Conditional#getCondition()
   * @see #getConditional()
   * @generated
   */
  EReference getConditional_Condition();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Conditional#getThenBranch <em>Then Branch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then Branch</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Conditional#getThenBranch()
   * @see #getConditional()
   * @generated
   */
  EReference getConditional_ThenBranch();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Conditional#getElseBranch <em>Else Branch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Branch</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Conditional#getElseBranch()
   * @see #getConditional()
   * @generated
   */
  EReference getConditional_ElseBranch();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Add <em>Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Add
   * @generated
   */
  EClass getAdd();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Add#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Add#getLeft()
   * @see #getAdd()
   * @generated
   */
  EReference getAdd_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Add#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Add#getRight()
   * @see #getAdd()
   * @generated
   */
  EReference getAdd_Right();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Subtract <em>Subtract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subtract</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Subtract
   * @generated
   */
  EClass getSubtract();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Subtract#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Subtract#getLeft()
   * @see #getSubtract()
   * @generated
   */
  EReference getSubtract_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Subtract#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Subtract#getRight()
   * @see #getSubtract()
   * @generated
   */
  EReference getSubtract_Right();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Multiply <em>Multiply</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiply</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Multiply
   * @generated
   */
  EClass getMultiply();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Multiply#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Multiply#getLeft()
   * @see #getMultiply()
   * @generated
   */
  EReference getMultiply_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Multiply#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Multiply#getRight()
   * @see #getMultiply()
   * @generated
   */
  EReference getMultiply_Right();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Divide <em>Divide</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Divide</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Divide
   * @generated
   */
  EClass getDivide();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Divide#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Divide#getLeft()
   * @see #getDivide()
   * @generated
   */
  EReference getDivide_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Divide#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Divide#getRight()
   * @see #getDivide()
   * @generated
   */
  EReference getDivide_Right();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Negate <em>Negate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Negate</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Negate
   * @generated
   */
  EClass getNegate();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Negate#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Negate#getValue()
   * @see #getNegate()
   * @generated
   */
  EReference getNegate_Value();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.Exponent <em>Exponent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exponent</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Exponent
   * @generated
   */
  EClass getExponent();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Exponent#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Exponent#getLeft()
   * @see #getExponent()
   * @generated
   */
  EReference getExponent_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.Exponent#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.Exponent#getRight()
   * @see #getExponent()
   * @generated
   */
  EReference getExponent_Right();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.NumberLiteral <em>Number Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Literal</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.NumberLiteral
   * @generated
   */
  EClass getNumberLiteral();

  /**
   * Returns the meta object for the attribute '{@link com.fearlesstyrant.sephirah.sephirah.NumberLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.NumberLiteral#getValue()
   * @see #getNumberLiteral()
   * @generated
   */
  EAttribute getNumberLiteral_Value();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.OrCondition <em>Or Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Condition</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.OrCondition
   * @generated
   */
  EClass getOrCondition();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.OrCondition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.OrCondition#getLeft()
   * @see #getOrCondition()
   * @generated
   */
  EReference getOrCondition_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.OrCondition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.OrCondition#getRight()
   * @see #getOrCondition()
   * @generated
   */
  EReference getOrCondition_Right();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.AndCondition <em>And Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Condition</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.AndCondition
   * @generated
   */
  EClass getAndCondition();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.AndCondition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.AndCondition#getLeft()
   * @see #getAndCondition()
   * @generated
   */
  EReference getAndCondition_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.AndCondition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.AndCondition#getRight()
   * @see #getAndCondition()
   * @generated
   */
  EReference getAndCondition_Right();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.NotCondition <em>Not Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not Condition</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.NotCondition
   * @generated
   */
  EClass getNotCondition();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.NotCondition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.NotCondition#getCondition()
   * @see #getNotCondition()
   * @generated
   */
  EReference getNotCondition_Condition();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.ComparisonCondition <em>Comparison Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison Condition</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.ComparisonCondition
   * @generated
   */
  EClass getComparisonCondition();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getLeft()
   * @see #getComparisonCondition()
   * @generated
   */
  EReference getComparisonCondition_Left();

  /**
   * Returns the meta object for the attribute '{@link com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getOp()
   * @see #getComparisonCondition()
   * @generated
   */
  EAttribute getComparisonCondition_Op();

  /**
   * Returns the meta object for the containment reference '{@link com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.ComparisonCondition#getRight()
   * @see #getComparisonCondition()
   * @generated
   */
  EReference getComparisonCondition_Right();

  /**
   * Returns the meta object for class '{@link com.fearlesstyrant.sephirah.sephirah.MethodCall <em>Method Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Call</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.MethodCall
   * @generated
   */
  EClass getMethodCall();

  /**
   * Returns the meta object for the attribute '{@link com.fearlesstyrant.sephirah.sephirah.MethodCall#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.MethodCall#getName()
   * @see #getMethodCall()
   * @generated
   */
  EAttribute getMethodCall_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.fearlesstyrant.sephirah.sephirah.MethodCall#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.MethodCall#getArgs()
   * @see #getMethodCall()
   * @generated
   */
  EReference getMethodCall_Args();

  /**
   * Returns the meta object for enum '{@link com.fearlesstyrant.sephirah.sephirah.ComparisonOperator <em>Comparison Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Comparison Operator</em>'.
   * @see com.fearlesstyrant.sephirah.sephirah.ComparisonOperator
   * @generated
   */
  EEnum getComparisonOperator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SephirahFactory getSephirahFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.FormulaModelImpl <em>Formula Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.FormulaModelImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getFormulaModel()
     * @generated
     */
    EClass FORMULA_MODEL = eINSTANCE.getFormulaModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMULA_MODEL__NAME = eINSTANCE.getFormulaModel_Name();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMULA_MODEL__IMPORTS = eINSTANCE.getFormulaModel_Imports();

    /**
     * The meta object literal for the '<em><b>Method Defs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMULA_MODEL__METHOD_DEFS = eINSTANCE.getFormulaModel_MethodDefs();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMULA_MODEL__VARIABLES = eINSTANCE.getFormulaModel_Variables();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMULA_MODEL__VALUES = eINSTANCE.getFormulaModel_Values();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.DocNameImpl <em>Doc Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.DocNameImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getDocName()
     * @generated
     */
    EClass DOC_NAME = eINSTANCE.getDocName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOC_NAME__NAME = eINSTANCE.getDocName_Name();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.ImportImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__NAME = eINSTANCE.getImport_Name();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.StatementImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.DefinitionImpl <em>Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.DefinitionImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getDefinition()
     * @generated
     */
    EClass DEFINITION = eINSTANCE.getDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINITION__NAME = eINSTANCE.getDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__ARGS = eINSTANCE.getDefinition_Args();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__EXPR = eINSTANCE.getDefinition_Expr();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.AssignmentImpl <em>Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.AssignmentImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getAssignment()
     * @generated
     */
    EClass ASSIGNMENT = eINSTANCE.getAssignment();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGNMENT__NAME = eINSTANCE.getAssignment_Name();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.VariableImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.EvaluationImpl <em>Evaluation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.EvaluationImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getEvaluation()
     * @generated
     */
    EClass EVALUATION = eINSTANCE.getEvaluation();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVALUATION__EXPRESSION = eINSTANCE.getEvaluation_Expression();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.ExpressionImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.ConditionImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ConstantImpl <em>Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.ConstantImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getConstant()
     * @generated
     */
    EClass CONSTANT = eINSTANCE.getConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__VALUE = eINSTANCE.getConstant_Value();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.VariableAssignmentImpl <em>Variable Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.VariableAssignmentImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getVariableAssignment()
     * @generated
     */
    EClass VARIABLE_ASSIGNMENT = eINSTANCE.getVariableAssignment();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_ASSIGNMENT__VALUE = eINSTANCE.getVariableAssignment_Value();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.DefinitionVariableImpl <em>Definition Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.DefinitionVariableImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getDefinitionVariable()
     * @generated
     */
    EClass DEFINITION_VARIABLE = eINSTANCE.getDefinitionVariable();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ConditionalImpl <em>Conditional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.ConditionalImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getConditional()
     * @generated
     */
    EClass CONDITIONAL = eINSTANCE.getConditional();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL__CONDITION = eINSTANCE.getConditional_Condition();

    /**
     * The meta object literal for the '<em><b>Then Branch</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL__THEN_BRANCH = eINSTANCE.getConditional_ThenBranch();

    /**
     * The meta object literal for the '<em><b>Else Branch</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL__ELSE_BRANCH = eINSTANCE.getConditional_ElseBranch();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.AddImpl <em>Add</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.AddImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getAdd()
     * @generated
     */
    EClass ADD = eINSTANCE.getAdd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD__LEFT = eINSTANCE.getAdd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD__RIGHT = eINSTANCE.getAdd_Right();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.SubtractImpl <em>Subtract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SubtractImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getSubtract()
     * @generated
     */
    EClass SUBTRACT = eINSTANCE.getSubtract();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBTRACT__LEFT = eINSTANCE.getSubtract_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBTRACT__RIGHT = eINSTANCE.getSubtract_Right();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.MultiplyImpl <em>Multiply</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.MultiplyImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getMultiply()
     * @generated
     */
    EClass MULTIPLY = eINSTANCE.getMultiply();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLY__LEFT = eINSTANCE.getMultiply_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLY__RIGHT = eINSTANCE.getMultiply_Right();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.DivideImpl <em>Divide</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.DivideImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getDivide()
     * @generated
     */
    EClass DIVIDE = eINSTANCE.getDivide();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVIDE__LEFT = eINSTANCE.getDivide_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVIDE__RIGHT = eINSTANCE.getDivide_Right();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.NegateImpl <em>Negate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.NegateImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getNegate()
     * @generated
     */
    EClass NEGATE = eINSTANCE.getNegate();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEGATE__VALUE = eINSTANCE.getNegate_Value();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ExponentImpl <em>Exponent</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.ExponentImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getExponent()
     * @generated
     */
    EClass EXPONENT = eINSTANCE.getExponent();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPONENT__LEFT = eINSTANCE.getExponent_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPONENT__RIGHT = eINSTANCE.getExponent_Right();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.NumberLiteralImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getNumberLiteral()
     * @generated
     */
    EClass NUMBER_LITERAL = eINSTANCE.getNumberLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_LITERAL__VALUE = eINSTANCE.getNumberLiteral_Value();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.OrConditionImpl <em>Or Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.OrConditionImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getOrCondition()
     * @generated
     */
    EClass OR_CONDITION = eINSTANCE.getOrCondition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_CONDITION__LEFT = eINSTANCE.getOrCondition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_CONDITION__RIGHT = eINSTANCE.getOrCondition_Right();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.AndConditionImpl <em>And Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.AndConditionImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getAndCondition()
     * @generated
     */
    EClass AND_CONDITION = eINSTANCE.getAndCondition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_CONDITION__LEFT = eINSTANCE.getAndCondition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_CONDITION__RIGHT = eINSTANCE.getAndCondition_Right();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.NotConditionImpl <em>Not Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.NotConditionImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getNotCondition()
     * @generated
     */
    EClass NOT_CONDITION = eINSTANCE.getNotCondition();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT_CONDITION__CONDITION = eINSTANCE.getNotCondition_Condition();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.ComparisonConditionImpl <em>Comparison Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.ComparisonConditionImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getComparisonCondition()
     * @generated
     */
    EClass COMPARISON_CONDITION = eINSTANCE.getComparisonCondition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON_CONDITION__LEFT = eINSTANCE.getComparisonCondition_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON_CONDITION__OP = eINSTANCE.getComparisonCondition_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON_CONDITION__RIGHT = eINSTANCE.getComparisonCondition_Right();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.impl.MethodCallImpl <em>Method Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.impl.MethodCallImpl
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getMethodCall()
     * @generated
     */
    EClass METHOD_CALL = eINSTANCE.getMethodCall();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_CALL__NAME = eINSTANCE.getMethodCall_Name();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_CALL__ARGS = eINSTANCE.getMethodCall_Args();

    /**
     * The meta object literal for the '{@link com.fearlesstyrant.sephirah.sephirah.ComparisonOperator <em>Comparison Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.fearlesstyrant.sephirah.sephirah.ComparisonOperator
     * @see com.fearlesstyrant.sephirah.sephirah.impl.SephirahPackageImpl#getComparisonOperator()
     * @generated
     */
    EEnum COMPARISON_OPERATOR = eINSTANCE.getComparisonOperator();

  }

} //SephirahPackage
