/**
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.sephirah.impl;

import com.fearlesstyrant.sephirah.sephirah.Condition;
import com.fearlesstyrant.sephirah.sephirah.SephirahPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConditionImpl extends MinimalEObjectImpl.Container implements Condition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConditionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SephirahPackage.Literals.CONDITION;
  }

} //ConditionImpl
