/**
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah.sephirah.impl;

import com.fearlesstyrant.sephirah.sephirah.DefinitionVariable;
import com.fearlesstyrant.sephirah.sephirah.SephirahPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Definition Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DefinitionVariableImpl extends AssignmentImpl implements DefinitionVariable
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefinitionVariableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SephirahPackage.Literals.DEFINITION_VARIABLE;
  }

} //DefinitionVariableImpl
