/*
 * generated by Xtext 2.42.0
 */
package com.fearlesstyrant.sephirah;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SephirahStandaloneSetup extends SephirahStandaloneSetupGenerated {

	public static void doSetup() {
		new SephirahStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
